### PR TITLE
Add CheckStyle and fix violations

### LINKED ISSUE #22: Project requires automatic code style checks
Add CodeStyle plugin to the project so that code style violations prevent the project from compiling.

### PR DESCRIPTION
**Pull request by nibsi**
resolves #22

### CODE REVIEW

File: core/src/main/java/com/coderanch/blackjack/Card.java [hunk 1]
```diff
@@ -57,7 +64,7 @@
      * @return the rank of this card; never {@code null}.
      */
     Rank rank() {
-        return this.rank;
+      return this.rank;
```
Comment (CoderanchClover) [inline core/src/main/java/com/coderanch/blackjack/Card.java]: This change should have been caught by style analysis.

**Review by liutaurasvilda — DISMISSED** [review]

**Review by CoderanchClover — APPROVED** [review]
